packages:
    - "packages/**"
    - "examples/**"
    - "website"
linkWorkspacePackages: true
saveWorkspaceProtocol: true
allowBuilds:
    "@swc/core": true
    esbuild: true
    nx: true
    sharp: true
minimumReleaseAgeExclude:
    - svelte@5.56.9
