packages:
    - "packages/**"
    - "examples"
    - "website"
linkWorkspacePackages: true
saveWorkspaceProtocol: true
allowBuilds:
    "@swc/core": true
    esbuild: true
    koffi: true
    nx: true
    sharp: true
minimumReleaseAgeExclude:
    - svelte@5.56.9
overrides:
    "astro-icon>@iconify/tools": 5.0.12
    "nx>brace-expansion": 5.0.9
    "@lhci/cli>tmp": 0.2.7
    "external-editor>tmp": 0.2.7
patchedDependencies:
    "@vitejs/plugin-vue@6.0.8": patches/@vitejs__plugin-vue@6.0.8.patch
